# Generated by Django 5.1.2 on 2024-10-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submissiondate',
            new_name='submission_date',
        ),
    ]
